runtime: nodejs18
env: standard
instance_class: F1
handlers:
  - url: .*
    script: auto
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
service_account: expoactiva-nacional-395522@appspot.gserviceaccount.com
env_variables:
  MONGO_URI: 'mongodb+srv://lazaroborghi:Lazaro$23@fstodo.xcdkqom.mongodb.net/?retryWrites=true&w=majority'
  KEY: 'KTKNCYB3RSOFT51117587.-'
  NODE_ENV: 'production'
