runtime: nodejs18
env: flex
entrypoint: npm start

automatic_scaling:
  target_cpu_utilization: 0.65
  min_num_instances: 1
  max_num_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10
